version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-optimizer-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - resume-optimizer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume-optimizer-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - resume-optimizer-network

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    container_name: resume-optimizer-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    profiles:
      - production
    networks:
      - resume-optimizer-network

networks:
  resume-optimizer-network:
    driver: bridge

volumes:
  backend-data: 