services:
  - type: web
    name: hireme-maker-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONIOENCODING
        value: utf-8
      # Optional: set in Render dashboard for production
      # - key: GEMINI_API_KEY
      #   sync: false

